import type {
  OrbitalPresetConfig,
  OrbitalPresetName,
} from '../OrbitalVisual.types';

const atomicOrbBase: OrbitalPresetConfig = {
  coreKind: 'atomic',

  coreRgb: '214 245 255',
  glowRgb: '114 220 255',
  accentRgb: '116 140 255',
  hotRgb: '255 255 255',

  ringCount: 3,
  baseRadius: 0.92,
  ringThickness: 0.0115,

  coreSize: 0.18,
  haloSize: 0.5,
  haloOpacity: 0.04,
  coreGlowOpacity: 0.2,
  coreInnerOpacity: 0.98,

  families: [
    {
      radiusScale: 1.1,
      ellipseX: 1.05,
      ellipseY: 1.08,
      tiltX: 0.05,
      tiltY: 1.16,
      tiltZ: 0.14,
      wobble: 0.006,
      heroThicknessScale: 1.22,
      heroOpacity: 0.7,
      flowSpeed: 0.285,
      rotationSpeed: 0,
      shimmerSpeed: 0.88,
      heroAccentMix: 0.08,
      echoAccentMix: 0.04,
      hotColorMix: 0.06,
      driftX: 0,
      driftY: 0,
      driftZ: 0,
      spinX: 0,
      spinY: 0,
      spinZ: 0,
      breath: 0,
      echoes: [],
      nodes: {
        count: 2,
        size: 0.024,
        glowSize: 1.6,
        speed: 0.1,
        offset: 0.08,
      },
    },
    {
      mirrorX: false,
      radiusScale: 1.01,
      ellipseX: 1.34,
      ellipseY: 0.84,
      tiltX: 0.76,
      tiltY: 0.18,
      tiltZ: 0.4,
      wobble: 0.0065,
      heroThicknessScale: 1.18,
      heroOpacity: 0.64,
      flowSpeed: 0.295,
      rotationSpeed: 0,
      shimmerSpeed: 0.92,
      heroAccentMix: 0.18,
      echoAccentMix: 0.1,
      hotColorMix: 0.07,
      driftX: 0,
      driftY: 0,
      driftZ: 0,
      spinX: 0,
      spinY: 0,
      spinZ: 0,
      breath: 0,
      echoes: [],
      nodes: {
        count: 3,
        size: 0.024,
        glowSize: 1.58,
        speed: 0.106,
        offset: 0.24,
      },
    },
    {
      mirrorX: true,
      radiusScale: 1.01,
      ellipseX: 1.34,
      ellipseY: 0.84,
      tiltX: 0.76,
      tiltY: 0.18,
      tiltZ: 0.4,
      wobble: 0.0065,
      heroThicknessScale: 1.18,
      heroOpacity: 0.64,
      flowSpeed: 0.295,
      rotationSpeed: 0,
      shimmerSpeed: 0.92,
      heroAccentMix: 0.18,
      echoAccentMix: 0.1,
      hotColorMix: 0.07,
      driftX: 0,
      driftY: 0,
      driftZ: 0,
      spinX: 0,
      spinY: 0,
      spinZ: 0,
      breath: 0,
      echoes: [],
      nodes: {
        count: 3,
        size: 0.024,
        glowSize: 1.58,
        speed: 0.106,
        offset: 0.24,
      },
    },
  ],
};

export const orbitalPresets = {
  'atomic-orb': atomicOrbBase,

  'atomic-orb-no-electrons': {
    ...atomicOrbBase,
    families: atomicOrbBase.families.map((family) => ({
      ...family,
      nodes: {
        ...family.nodes,
        count: 0,
      },
    })),
  },

  'atomic-orb-more-electrons': {
    ...atomicOrbBase,
    families: atomicOrbBase.families.map((family, index) => {
      const counts = [4, 6, 6];
      const sizes = [0.022, 0.022, 0.022];
      const glowSizes = [1.52, 1.5, 1.5];

      return {
        ...family,
        nodes: {
          ...family.nodes,
          count: counts[index] ?? family.nodes.count,
          size: sizes[index] ?? family.nodes.size,
          glowSize: glowSizes[index] ?? family.nodes.glowSize,
        },
      };
    }),
  },

  'atomic-orb-white': {
    ...atomicOrbBase,
    coreRgb: '236 248 255',
    glowRgb: '205 232 255',
    accentRgb: '182 208 255',
    hotRgb: '255 255 255',
    haloOpacity: 0.045,
    coreGlowOpacity: 0.22,
    families: atomicOrbBase.families.map((family) => ({
      ...family,
      heroOpacity: Math.min(family.heroOpacity + 0.04, 0.78),
      heroAccentMix: Math.max(family.heroAccentMix - 0.04, 0.04),
      hotColorMix: Math.max(family.hotColorMix - 0.02, 0.04),
    })),
  },

  'atomic-orb-violet': {
    ...atomicOrbBase,
    coreRgb: '228 220 255',
    glowRgb: '171 126 255',
    accentRgb: '118 102 255',
    hotRgb: '255 244 255',
    haloOpacity: 0.045,
    coreGlowOpacity: 0.22,
    families: atomicOrbBase.families.map((family) => ({
      ...family,
      heroAccentMix: Math.min(family.heroAccentMix + 0.08, 0.32),
      echoAccentMix: Math.min(family.echoAccentMix + 0.06, 0.22),
      hotColorMix: Math.min(family.hotColorMix + 0.04, 0.14),
    })),
  },

  'ring-planet': {
    coreKind: 'planet',

    coreRgb: '128 205 255',
    glowRgb: '58 160 255',
    accentRgb: '42 98 220',
    hotRgb: '235 250 255',

    ringCount: 2,
    baseRadius: 0.98,
    ringThickness: 0.0195,

    coreSize: 0.7,
    haloSize: 0.32,
    haloOpacity: 0.008,
    coreGlowOpacity: 0.04,
    coreInnerOpacity: 1,

    families: [
      {
        // Внешнее толстое кольцо — основная планетная плоскость
        radiusScale: 1.16,
        ellipseX: 1.48,
        ellipseY: 0.36,
        tiltX: -0.28,
        tiltY: 0.04,
        tiltZ: -0.08,
        wobble: 0.0025,
        heroThicknessScale: 2.35,
        heroOpacity: 0.76,
        flowSpeed: 0.11,
        rotationSpeed: 0,
        shimmerSpeed: 0.42,
        heroAccentMix: 0.08,
        echoAccentMix: 0.03,
        hotColorMix: 0.04,
        driftX: 0,
        driftY: 0,
        driftZ: 0,
        spinX: 0,
        spinY: 0,
        spinZ: 0,
        breath: 0,
        echoes: [],
        nodes: {
          count: 0,
          size: 0.022,
          glowSize: 1.4,
          speed: 0.08,
          offset: 0.1,
        },
      },
      {
        // Внутреннее кольцо — та же плоскость, меньший радиус
        radiusScale: 0.92,
        ellipseX: 1.48,
        ellipseY: 0.36,
        tiltX: -0.28,
        tiltY: 0.04,
        tiltZ: -0.08,
        wobble: 0.0025,
        heroThicknessScale: 1.65,
        heroOpacity: 0.48,
        flowSpeed: 0.09,
        rotationSpeed: 0,
        shimmerSpeed: 0.36,
        heroAccentMix: 0.12,
        echoAccentMix: 0.04,
        hotColorMix: 0.04,
        driftX: 0,
        driftY: 0,
        driftZ: 0,
        spinX: 0,
        spinY: 0,
        spinZ: 0,
        breath: 0,
        echoes: [],
        nodes: {
          count: 0,
          size: 0.022,
          glowSize: 1.4,
          speed: 0.08,
          offset: 0.34,
        },
      },
    ],
  },
} satisfies Record<OrbitalPresetName, OrbitalPresetConfig>;